# Use a Java base image
FROM eclipse-temurin:17-jdk

# Create a working directory inside the container
WORKDIR /app

# Copy the .jar file generated by Maven
COPY target/urlshortener-0.0.1-SNAPSHOT.jar app.jar

# Expose the port your app uses
EXPOSE 8080

# Command to run when the container starts
ENTRYPOINT ["java", "-jar", "app.jar"]
